---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
before_install: gem install bundler -v 1.3

script:
  - bundle exec rspec
  - bundle exec rubocop