trigger: none
pr:
  - master

resources:
  repositories:
    - repository: SharedTemplates
      type: git
      name: "Infrastructure/iss-shared-terraform"
      ref: refs/tags/2024.08.22

variables:
  - group: terraform
  - group: snyk
  - name: snykProject
    value: 'Tririga Connector'

pool: $(selfHostedAgentPool)

steps:
  - checkout: self
    
  - script: |
      docker run -a stdin -a stdout -a stderr -v $(System.DefaultWorkingDirectory):/usr/app ruby:2.7.5 /bin/bash -c 'cd /usr/app && gem install bundler -v 2.4.22 && bundle install'
    displayName: Install ruby packages
    
  - template: tasks/snyk_task.yaml@SharedTemplates
    parameters:
      scanType: code
      connection: $(snyk_connection)
      organizationId: $(snyk_organization_id)
      snykProjects:
        - name: ${{ variables.snykProject }}
          path: ''
          ${{ if eq(variables['build.sourceBranch'], 'master') }}:
            monitor: 'always'
          ${{ else }}:
            monitor: 'never'

  - template: tasks/snyk_task.yaml@SharedTemplates
    parameters:
      scanType: package
      connection: $(snyk_connection)
      organizationId: $(snyk_organization_id)
      snykProjects:
        - name: ${{ variables.snykProject }}
          path: ''
          targetFile: 'Gemfile'
          ${{ if eq(variables['build.sourceBranch'], 'master') }}:
            monitor: 'always'
          ${{ else }}:
            monitor: 'never'